apiVersion: v1
kind: Pod
metadata:
  name: test-job
spec:
  containers:
    - name: test-container
      image: curlimages/curl
      command: ["/bin/sh", "-c", "sleep 5000"]
  restartPolicy: OnFailure
