apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dobby-rs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dobby-pod
  template:
    metadata:
      labels:
        app: dobby-pod
    spec:
      containers:
        - name: dobby
          image: thecasualcoder/dobby
          ports:
            - containerPort: 4444