apiVersion: apps/v1
kind: Deployment
metadata:
  name: dobby
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dobby-pod
  template:
    metadata:
      labels:
        app: dobby-pod
    spec:
      containers:
        - name: dobby
          image: thecasualcoder/dobby
          ports:
            - containerPort: 4444
          env:
            - name: VERSION
              value: "3.0"  