apiVersion: v1
kind: Service
metadata:
  name: metadata-service-np
spec:
  type: NodePort
  selector:
    app: metadata-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: metadata-service-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadata-service
  template:
    metadata:
      labels:
        app: metadata-service
    spec:
      containers:
        - name: metadata-service
          image: sunitparekh/metadata:v1.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 3